name: '2025.07.$(Build.BuildId)'
trigger: none

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: sunilkumarsukesan/TestAutomationHub
      endpoint: sunilkumarsukesan (1)
    - repository: githubRepo1
      type: github
      name: sunilkumarsukesan/webdriverio-framework
      endpoint: sunilkumarsukesan (1)

pool:
  name: 'Azure Pipelines'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: githubRepo

          - script: |
              npm install
              npm run build
            displayName: 'Build and Generate Dist'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: 'react-dist'
              publishLocation: 'Container'

  - stage: Dev_Deploy
    dependsOn: Build
    jobs:
      - job: DeployToDev
        steps:
          - download: current
            artifact: react-dist

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'  # You must define this service connection
              sourceFolder: '$(Pipeline.Workspace)/react-dist'
              targetFolder: '/home/sunilsukesan/react-app'
              cleanTargetFolder: true
              overwrite: true

          - task: SSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'
              runOptions: 'inline'
              inline: |
                echo "🔄 Cleaning up any previous serve process..."
                PID=$(sudo lsof -t -i:5173 || true)
                if [ ! -z "$PID" ]; then
                  echo "Killing process on 5173 (PID: $PID)..."
                  sudo kill -9 $PID
                else
                  echo "No process running on 5173"
                fi

                echo "🧹 Cleaning previous PM2 processes..."
                pm2 delete all || true
                pm2 save || true

                echo "📦 Ensuring PM2 and serve are installed..."
                sudo npm install -g pm2 serve

                echo "🚀 Starting app using PM2 serve..."
                cd /home/sunilsukesan/react-app/dist
                pm2 start "npx serve -s . -l 5173" --name react-app
                pm2 save
                pm2 startup --silent
            displayName: 'SSH: Cleanup + Serve React App'



