name: '2025.07.$(Build.BuildId)'
trigger: none

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: sunilkumarsukesan/TestAutomationHub
      endpoint: sunilkumarsukesan (1)
    - repository: githubRepo1
      type: github
      name: sunilkumarsukesan/webdriverio-framework
      endpoint: sunilkumarsukesan (1)

pool:
  name: 'Azure Pipelines'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: githubRepo

          - script: |
              npm install
              npm run build
            displayName: 'Build and Generate Dist'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: 'react-dist'
              publishLocation: 'Container'

  - stage: Dev_Deploy
    dependsOn: Build
    jobs:
      - job: DeployToDev
        steps:
          - download: current
            artifact: react-dist

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'  # You must define this service connection
              sourceFolder: '$(Pipeline.Workspace)/react-dist'
              targetFolder: '/home/sunilsukesan/react-app'
              cleanTargetFolder: true
              overwrite: true

          - task: SSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'
              runOptions: 'commands'
              commands: |
                cd /home/sunilsukesan/react-app
                
                # Install pm2 always (safe even if already exists)
                sudo npm install -g pm2

                # Stop old app quietly if it exists
                pm2 delete react-app 2>/dev/null || true

                # Enter dist folder
                cd dist

                # Start the app using serve via pm2
                pm2 start "npx serve -s . -l 5173" --name react-app

                # Save and enable restart on reboot
                pm2 save
                pm2 startup --silent
              failOnStdErr: false


