name: '2025.07.$(Build.BuildId)'
trigger: none

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: sunilkumarsukesan/TestAutomationHub
      endpoint: sunilkumarsukesan (1)

stages:
  - stage: Build
    displayName: Build React App
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: githubRepo

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies & build'

          - task: CopyFiles@2
            inputs:
              sourceFolder: '$(Build.SourcesDirectory)/dist'
              contents: '**'
              targetFolder: '$(Build.ArtifactStagingDirectory)/dist'
            displayName: 'Prepare artifact'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/dist'
              artifactName: 'dist'
            displayName: 'Publish dist as artifact'

  - stage: Deploy
    displayName: Deploy to Azure VM
    dependsOn: Build
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            artifact: dist

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'
              sourceFolder: '$(Pipeline.Workspace)/dist'
              contents: '**'
              targetFolder: '/home/sunilsukesan/react-app/dist'
              overwrite: true
            displayName: 'Copy dist to Azure VM'

          - task: SSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'
              runOptions: 'inline'
              inline: |
                echo "Killing any app on port 3000 or 5173"
                sudo fuser -k 3000/tcp || echo "Port 3000 already free"
                sudo fuser -k 5173/tcp || echo "Port 5173 already free"

                echo "Sleeping for 5 seconds"
                sleep 5

                echo "Starting the app in background"
                cd /home/sunilsukesan/react-app/dist
                nohup npx serve -s . > serve.log 2>&1 &
            displayName: 'Stop app, sleep, and serve new app'
