name: '2025.07.$(Build.BuildId)'
trigger: none

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: sunilkumarsukesan/TestAutomationHub
      endpoint: sunilkumarsukesan (1)

stages:
  - stage: SonarQube
    displayName: 'SonarQube Analysis'
    jobs:
      - job: RunSonar
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: githubRepo

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npx sonar-scanner \
                -Dsonar.projectKey=TestAutomationHub \
                -Dsonar.sources=. \
                -Dsonar.host.url=http://20.17.97.4:9000 \
                -Dsonar.token=sqp_40cbebf428b1dea9c2ad4d8be0e7cf59d60b9231
            displayName: 'Run SonarQube Scan'

  - stage: Build
    displayName: 'Build React App'
    dependsOn: SonarQube
    condition: succeeded()
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: githubRepo

          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build
            displayName: 'Install dependencies & build'

          - task: CopyFiles@2
            inputs:
              sourceFolder: '$(Build.SourcesDirectory)/dist'
              contents: '**'
              targetFolder: '$(Build.ArtifactStagingDirectory)/dist'
            displayName: 'Prepare artifact'

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/dist'
              artifactName: 'dist'
            displayName: 'Publish dist as artifact'

# Optional: You can remove or comment out the Deploy stage
#  - stage: Deploy
#    ...
