name: '2025.07.$(Build.BuildId)'
trigger: none

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: sunilkumarsukesan/TestAutomationHub
      endpoint: sunilkumarsukesan (1)
    - repository: githubRepo1
      type: github
      name: sunilkumarsukesan/webdriverio-framework
      endpoint: sunilkumarsukesan (1)

pool:
  name: 'Default'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: githubRepo
          - script: |
              npm install
              npm run dev
            displayName: 'Build dev App'

  - stage: Dev_Deploy
    dependsOn: Build
    jobs:
      - job: DeployToDev
        steps:
          - script: echo "Deploying to Dev..."

  - stage: Smoke_Tests
    dependsOn: Dev_Deploy
    jobs:
      - job: Smoke
        steps:
          - checkout: githubRepo1
          - script: |
              npm install
              npm run test
            displayName: 'Run Smoke Tests'
