name: '2025.07.$(Build.BuildId)'
trigger: none

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: sunilkumarsukesan/TestAutomationHub
      endpoint: sunilkumarsukesan (1)
    - repository: githubRepo1
      type: github
      name: sunilkumarsukesan/webdriverio-framework
      endpoint: sunilkumarsukesan (1)

pool:
  name: 'Azure Pipelines'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: githubRepo

          - script: |
              npm install
              npm run build
            displayName: 'Build and Generate Dist'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: 'react-dist'
              publishLocation: 'Container'

  - stage: Dev_Deploy
    dependsOn: Build
    jobs:
      - job: DeployToDev
        steps:
          - download: current
            artifact: react-dist

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'  # You must define this service connection
              sourceFolder: '$(Pipeline.Workspace)/react-dist'
              targetFolder: '/home/sunilsukesan/react-app'
              cleanTargetFolder: true
              overwrite: true

          - task: SSH@0
            inputs:
              sshEndpoint: 'ubuntu-free-vm'
              runOptions: 'commands'
              commands: |
                cd /home/sunilsukesan/react-app
                npx serve -s . -l 5173 > serve.log 2>&1 &
              failOnStdErr: false
              readyTimeout: '20000'